#!/bin/bash
sudo apt-add-repository ppa:alexlarsson/flatpak
sudo apt-add-repository ppa:nilarimogard/webupd8
sudo apt-add-repository ppa:libreoffice/ppa
sudo apt-add-repository ppa:noobslab/themes
sudo apt-add-repository ppa:ubuntu-desktop/ubuntu-make
sudo apt-add-repository ppa:fixnix/indicator-systemtray-unity
sudo apt-add-repository ppa:atareao/atareao
sudo apt-add-repository ppa:webupd8team/terminix
sudo apt-add-repository ppa:linrunner/tlp
sudo apt-add-repository ppa:ultradvorka/ppa
sudo apt-add-repository ppa:neovim-ppa/unstable
sudo apt-add-repository ppa:tista/adapta
sudo apt-add-repository ppa:webupd8team/y-ppa-manager
sudo apt-add-repository ppa:ansible/ansible
sudo apt-add-repository ppa:jonathonf/vim
sudo apt-add-repository ppa:ravefinity-project/ppa
sudo apt-add-repository ppa:nginx/stable
sudo apt-add-repository ppa:pipelight/stable
sudo apt-add-repository ppa:docker/stable
sudo apt-add-repository ppa:snwh/pulp
sudo apt-add-repository ppa:fingerprint/fingerprint-gui
sudo apt-add-repository ppa:eosrei/fonts
sudo apt-add-repository ppa:team-xbmc/ppa
sudo apt-add-repository ppa:webupd8team/atom
