#!/bin/bash
sudo apt-add-repository \'https://apt.dockerproject.org/repo ubuntu-xenial main\'
sudo apt-add-repository \'http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse\'
sudo apt-add-repository \'http://repository.spotify.com stable non-free\'
sudo apt-add-repository \'https://tel.red/repos/ubuntu yakkety non-free\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ yakkety main restricted\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ yakkety-updates main restricted\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ yakkety universe\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ yakkety-updates universe\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ yakkety multiverse\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ yakkety-updates multiverse\'
sudo apt-add-repository \'http://ie.archive.ubuntu.com/ubuntu/ yakkety-backports main restricted universe multiverse\'
sudo apt-add-repository \'http://security.ubuntu.com/ubuntu yakkety-security main restricted\'
sudo apt-add-repository \'http://security.ubuntu.com/ubuntu yakkety-security universe\'
sudo apt-add-repository \'http://security.ubuntu.com/ubuntu yakkety-security multiverse\'
