#!/bin/bash'
export NAME="Ryan Craig"
export EMAIL="ryan.craig@smartbox.com"

export CHEF_COOKBOOKS='/home/ryancrai/gitlab/chef-cookbooks'
export CHEF_DATA_BAGS='/home/ryancrai/gitlab/chef-data-bags'
export CHEF_ENVIRONMENTS='/home/ryancrai/gitlab/chef/environments'
export CHEF_ROLES='/home/ryancrai/gitlab/chef/roles'
export DOCKERFILES='/home/ryancrai/gitlab/dockerfiles'
export EDITOR='/usr/bin/vim'
export GITHUB='/home/ryancrai/github'
export GITLAB='/home/ryancrai/gitlab'
export GITLAB_TOKEN="$(cat ${HOME}/.gitlab_token)"
export __GIT_PROMPT_IGNORE_STASH=''
export GIT_PROMPT_ONLY_IN_REPO='0'
export __GIT_PROMPT_SHOW_CHANGED_FILES_COUNT='1'
export GIT_PROMPT_THEME='Single_line_Ubuntu'
export NR_API_KEY="$(cat ${HOME}/.newrelic_api_key)"
export PAGER='/usr/bin/most'
export PROD='production.smartbox.com'
export PROMPT_COMMAND='setLastCommandState;history -a; history -c; history -r; echo "$(history 1)" >> ~/.bash_eternal_history;setGitPrompt'
export PROMPT_DIRTRIM='2'
export SANDBOX='sandbox.local'
export VALID_FQDN='^(?=.{1,255}$)[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?(?:\.[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?)*\.?$'
export VALID_IP='[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
export VISUAL='/usr/bin/vim'
